### ISSUE TITLE
[UI/UX] Revamp the HUD

### ISSUE THREAD

**Issue by CactuarTamer** [CactuarTamer/SteamNoir#12]
Revamp the hud. This issue has too much stuff in it tbh. I sh

- [ ] Add a Nav Compass
- [ ] Move the menu to a top bar
- [ ] Display current location in top bar
- [ ] Add controls to right of word box, Nav compass + Talk/Look/inventory
